# Generated by Django 5.2.1 on 2025-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='listitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
