# Generated by Django 5.2.1 on 2025-06-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_listitem_item_listitem_name_listitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
