# Generated by Django 5.2.1 on 2025-06-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_listitem_search_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='kroger_upc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='location_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
